spring:
  application:
    name: text-polish-service

server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true

proofreading-service:
  name: proofreading-service
  url: http://localhost:3000
